pool: Linux-SelfHosted

variables:
  - group: vg-semantic-versioning

resources:
- repo: self

name: '$(major).$(minor).$(patch)'

stages:

- stage: Pack
  displayName: 'Package AMI Image'
  jobs:
  - job : Pack
    workspace:
      clean: all
    displayName: 'Pack AMI Image'
    steps:
      - task: UseDotNet@2
        displayName: 'Get latest .NET SDK'
        inputs:
          version: '3.1.300'